site_name: maya-zen-tools
site_url: https://davebelais.github.io/maya-zen-tools/
repo_url: https://github.com/davebelais/maya-zen-tools/
edit_uri: blob/main/docs/
nav:
- Introduction: 'index.md'
- CLI Reference: 'cli.md'
- API Reference:
    - download: 'api/download.md'
    - tag-version: 'api/tag_version.md'
- Contributing: 'contributing.md'
theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            inherited_members: true
            heading_level: 1
            separate_signature: true
            annotations_path: full
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - assets/stylesheets/style.css
extra_javascript:
  - assets/javascripts/extra.js
