site_name: ZenTools for Maya
site_url: https://enorganic.github.io/maya-zen-tools/
repo_url: https://github.com/enorganic/maya-zen-tools/
edit_uri: blob/main/docs/
nav:
- Introduction: 'index.md'
- Installation: 'installation.md'
- Selection:
  - Select Edges Between Vertices: 'selection/select-edges-between-vertices.md'
  - Select Edges Between UVs: 'selection/select-edges-between-uvs.md'
  - Select UVs Between UVs: 'selection/select-uvs-between-uvs.md'
  - Flood Select: 'selection/flood-select.md'
- Modeling:
  - Curve Distribute Between Vertices: 'modeling/curve-distribute-between-vertices.md'
  - Loft Distribute Vertices Between Edges: 'modeling/loft-distribute-vertices-between-edges.md'
- Texturing:
  - Curve Distribute Between UVs: 'texturing/curve-distribute-between-uvs.md'
  - Loft Distribute UVs Between Edges or UVs: 'texturing/loft-distribute-uvs-between-edges-or-uvs.md'
- API Reference:
  - errors: 'api/errors.md'
  - flood: 'api/flood.md'
  - install: 'api/install.md'
  - loft: 'api/loft.md'
  - loop: 'api/loop.md'
  - menu: 'api/menu.md'
  - options: 'api/options.md'
  - startup: 'api/startup.md'
- Contributing: 'contributing.md'
- Report a Bug: https://github.com/enorganic/maya-zen-tools/issues
theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            inherited_members: true
            heading_level: 1
            separate_signature: true
            annotations_path: full
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - assets/stylesheets/style.css
extra_javascript:
  - assets/javascripts/extra.js
