name: test
on:
  push:
    branches:
    - main
  workflow_dispatch:
  pull_request:
    paths:
    - src/**
    - pyproject.toml
    - tests/**
    - .github/workflows/test.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Hatch
      uses: pypa/hatch@install
    - run: hatch fmt --check
  # Testing isn't possible without licensed copies of maya :-P
  # test:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os:
  #       - ubuntu-latest
  #       - windows-latest
  #       - macos-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install Hatch
  #     uses: pypa/hatch@install
  #   - name: test
  #     run: make test
